### ISSUE TITLE
Logo overlaps with the nav  bar icons

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/Biosimulations#325]
Feedback reported on **Fri Jan 24 2020** at **12:43:11** (GMT-0500)  from **[https://biosimulations.herokuapp.com/](https://biosimulations.herokuapp.com/)** 

### Comments

> Logo overlaps with the nav  bar icons

### date

> 2020-01-24T17:42:47.245Z

--------------------------------------------------------------------------------------------------

## Context

* Browser : **Chrome 79.0** ([Supported features](https://caniuse.com/#compare=chrome+79))
* Operating System : **Windows 8.1**
* Display : **1920 x 1080** 
* Language : **English** 🇺🇸
* IP / Location : **146.203.121.24** (*[New York, New York, US](https://www.google.com/maps/search/?api=1&query=40.7128,-74.0059)*)
* Network : **5.95Mbps** (down) / **4g** ([ECT](http://wicg.github.io/netinfo/#effective-connection-types))
*  Cookies : 
    * auth0.is.authenticated = true

 *Generated by Bruit.io. If you like it, let it be known !* [![Github Logo](https://bruit.io/assets/logos/github.png "Github logo")](https://github.com/moventes/bruit.io) [![Twitter Logo](https://bruit.io/assets/logos/twitter.png "Twitter logo")](https://twitter.com/intent/tweet?text=https%3A%2F%2Fbruit.io+is+an+awesome+tool+%21++%23userfeedback+%23bugreporting+%23webdev)

![1579887820214.screenshot.png](https://github.com/reproducible-biomedical-modeling/BioSimulations-feedback/blob/master/1579887820214.screenshot.png?raw=true) 
[1579887823347.application.log](https://github.com/reproducible-biomedical-modeling/BioSimulations-feedback/blob/master/1579887823347.application.log)

**Comment by bilalshaikh42** [comment]
add bottom padding of 20 to the mat-top-bar class
