### ISSUE TITLE
Component scrolls off top of page

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/Biosimulations#409]
Feedback reported on **Thu Mar 19 2020** at **11:01:54** (GMT-0400)  from **[http://localhost:4200/models/003/edit](http://localhost:4200/models/003/edit)** 

### Comments

> Component scrolls off top of page

### date

> 2020-03-19T14:57:29.018Z

### user

> google-oauth2|101683931106741052527

--------------------------------------------------------------------------------------------------

## Context

* Browser : **Chrome 80.0** ([Supported features](https://caniuse.com/#compare=chrome+80))
* Operating System : **Linux x86_64**
* Display : **1920 x 1080** 
* Language : **English** 🇺🇸
* IP / Location : **158.222.223.212** (*[New York, New York, US](https://www.google.com/maps/search/?api=1&query=40.7999,-73.9683)*)
* Network : **10Mbps** (down) / **4g** ([ECT](http://wicg.github.io/netinfo/#effective-connection-types))
*  Cookies : 
    * auth0.is.authenticated = true

 *Generated by Bruit.io. If you like it, let it be known !* [![Github Logo](https://bruit.io/assets/logos/github.png "Github logo")](https://github.com/moventes/bruit.io) [![Twitter Logo](https://bruit.io/assets/logos/twitter.png "Twitter logo")](https://twitter.com/intent/tweet?text=https%3A%2F%2Fbruit.io+is+an+awesome+tool+%21++%23userfeedback+%23bugreporting+%23webdev)

![1584630116365.screenshot.png](https://github.com/reproducible-biomedical-modeling/BioSimulations-feedback/blob/master/1584630116365.screenshot.png?raw=true) 
[1584630118715.application.log](https://github.com/reproducible-biomedical-modeling/BioSimulations-feedback/blob/master/1584630118715.application.log)

**Comment by bilalshaikh42** [comment]
fixed
