### ISSUE TITLE
Align Visualization data model with other data models

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/Biosimulations#443]
- Add `format` property (`format: Format`)
- Remove `data` property. Instead, this should be computed from `layout[].data[].simulation_results`.

**Comment by bilalshaikh42** [comment]
is the format property the same as the Format type?

**Comment by jonrkarr** [comment]
Yes. I had excluded this originally because all Visualizations will be in Vega format. To better align the resources (models, simulations, visualizations), I think it could be good to explicitly track the format. The value would always be set to Vega (or Vega lite).

**Comment by bilalshaikh42** [comment]
Got it.
Should both visualization and chart have this?

best
Bilal

**Comment by jonrkarr** [comment]
That makes sense.

The one resource that doesn't have a clear format is Project. COMBINE archive (zip file) would be the closest, but we shouldn't advertise that format on the website until the application can compile a project to a COMBINE archive.
