### ISSUE TITLE
Add properties to `Algorithm` data model

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/Biosimulations#459]
- `kisaoId`: `string`
- `synonymousKisaoIds`: `string[]`
- `modelingFrameworks`: `OntologyTerm[]`
- `modelFormats`: `Format[]`

Also, the comment that `id` is used for KiSAO ids should be removed; instead, `id` should be used to capture the ids that software tools use internally to indicate algorithms. Different software tools may use the different ids to indicate the same algorithm (i.e. same KiSAO id).

**Comment by bilalshaikh42** [comment]
Would the following work for this? 

`
interface Algorithm {
    id: string 
    name: string
    ontologyTerms: OntologyTerm []
    modelingFrameworks: OntologyTerm[]
   modelFormats: Format[]

`
Ontology term would be used to describe KISAO, SBO and EDAM ids

**Comment by jonrkarr** [comment]
(a) Algorithm needs to have a list of algorithm parameters
```
parameters: AlgorithmParameter[]
```

(b) I think we need to separately capture the main KiSAO term because this has to be passed to SED-ML in a particular way. This can be implemented with OntologyTerm. The `ontology` attribute of the term will need to be constrained to be `KISAO`.
```
kisaoId: OntologyTerm
ontologyTerms: OntologyTerm[]
```

`ontologyTerms` can be used to capture additional terms from any ontology.

**Comment by bilalshaikh42** [comment]
Got it. How does this look? 
```
interface Algorithm {
    id: string 
    name: string
    kisaoTerm: KisaoTerm
    ontologyTerms:  OntologyTerm []
    modelingFrameworks: OntologyTerm[]
    modelFormats: Format[]
}

interface OntologyTerm{
    ontology: string
    id: string
    // Name description, iri can be pulled from metadata service or computed or included in "ontologyInformation"
}

interface KisaoTerm extends OntologyTerm{
    ontology: "kisao"
    id: string 
}
```
The same idea would apply to anything else that needs a SBO, KISAO, or EDAM id

**Comment by jonrkarr** [comment]
(a) Algorithm looks good.

(b) In principle, the name, description, and IRI for OntologyTerms can be computed. In practice, I think it would be good to cache this information so it can be returned without having to compute it out of an ontology file. Furthermore, users may want to use ontologies that we don't haven't setup access to. Because there's no single repository of ontologies, it's difficult to setup access to all possible ontologies.
