### ISSUE TITLE
Add properties to `Format` model

### ISSUE THREAD

**Issue by jonrkarr** [reproducible-biomedical-modeling/Biosimulations#462]
- `id`: `string`
- `spec_url`: `string` (URL for specification of format; needed by COMBINE format)

**Comment by bilalshaikh42** [comment]
Can this also be changed to modelformat?

**Comment by jonrkarr** [comment]
This shouldn't be renamed to `ModelFormat` because this will be used to represent model formats, simulation formats, archive formats, visualization formats, etc.

**Comment by bilalshaikh42** [comment]
Got it
